apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-public
    resourceVersion: '208'
    uid: fd0a7842-4612-43d2-b381-3bdbe398bb06
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resourceNames:
    - cluster-info
    resources:
    - configmaps
    verbs:
    - update
  - apiGroups:
    - ''
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: '201'
    uid: 253d0329-7279-4b71-b1ed-d2554b4f0a92
  rules:
  - apiGroups:
    - ''
    resourceNames:
    - extension-apiserver-authentication
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: '206'
    uid: d221991c-d97d-40a6-8437-e76641bc98f3
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ''
    resourceNames:
    - kube-controller-manager
    resources:
    - configmaps
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: '207'
    uid: c999d020-bc8c-43ee-a995-697b2be301a3
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ''
    resourceNames:
    - kube-scheduler
    resources:
    - configmaps
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: '203'
    uid: 253fd77a-78b8-4f96-9a21-7dc8c861db2e
  rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: '204'
    uid: e921f10f-9cc7-4e31-9c2c-2b46dd55e111
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: 'true'
    creationTimestamp: '2025-09-27T19:56:29Z'
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: '205'
    uid: 232eeec8-d287-470b-8940-4b5df0e01773
  rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - ''
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
    - patch
    - update
kind: List
metadata:
  resourceVersion: ''
