apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-database-tier
spec:
  podSelector:
    matchLabels:
      subnet: database-tier
  policyTypes:
  - Ingress
  - Egress
